### Check the integration
GET http://localhost:3000/dune

### Check the oldness of a movie
GET http://localhost:3000/movies/batman/oldness

# Oldness categories:
# oldness: old/new/90s
# old: anything before 1990
# 90s: 1990 to 2000
# new: 2000 to present

### Check the profitability of a movie
GET http://localhost:3000/movies/batman/profitability

# Profitability categories:
# profitability: PROFITABLE / NON-PROFITABLE / BLOCKBUSTER
# 
# difference = made - budget
# difference > 100 => BLOCKBUSTER
# difference > 0 => PROFITABLE
# difference <= 0 => NON-PROFITABLE


### Check the rating of a movie
GET http://localhost:3000/movies/batman/rating

# Rating limit (out of 10)
# 0 to 10

# actual return rating ( out of 5)
# actual = current / 2